pipeline {
    agent { docker { image "cart.lge.com/swte/host-test-dev:latest" } }
    stages {
        stage('Test') {
            steps {
                dir("unittest") {
                    sh "python3 -m pytest --tb=long -xvv --junitxml unittest.xml"
                }
            }
        }
        stage('Report') {
            steps {
                junit 'unittest/unittest.xml'
            }
        }
    }  // stages
    post {
        always {
            cleanWs()
        }
    }  // post
}  // pipeline
